version: '3.2'
services:
  web:
    build: .
    container_name: check-email
    ports:
      - '80:80'
    networks:
      - eec
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ../db/:/var/lib/postgresql/data
    restart: always
    networks:
      - eec

networks:
  eec:
    driver: bridge
